# This is a basic workflow to help you get started with Actions

name: CI

on: workflow_dispatch   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          repository: https://github.com/AlabamaWaterInstitute
          # Destination branch to push changes
          branch: main
